### ISSUE TITLE
Job status

### ISSUE THREAD

**Issue by yaghmr** [seomoz/qless-py#20]
In addition to the notifications how I get the status ('canceled', 'completed', 'failed'...) of a job?

**Comment by dlecocq** [comment]
```python
# For example, finding a job based on its job id
job = client.jobs['some-job-id']
if job == None:
    # It's possible the job is canceled or was completed, but expired from the system
    print 'Canceled or expired'
else:
    # Otherwise, use job.state
    print job.state
```

**Comment by yaghmr** [comment]
Thanks. Another question:
Is possible to choose a unique name for a job?

**Comment by dlecocq** [comment]
Yes. By default, when creating a job a UUID is used:

```python
# Here a UUID is used as the job id
client.queues['my-queue'].put(JobClass, {'my': 'data'})
```

But you can also provide one of your own if your application logic calls for it:

```python
client.queues['my-queue'].put(JobClass, {'my': 'data'}, jid='my-special-job-id')
```

It's worth noting that if you then try to put another job with the same job id in another queue, it's equivalent to moving the original job and has all the associated repercussions.

**Comment by yaghmr** [comment]
And what happen if I use the same job id in the same queue? The second job is ignored?

**Comment by dlecocq** [comment]
In that case, it's equivalent to re-enqueing the job. If it had previously been popped and worked on by a worker, it will be taken away from that work and get in line again.

**Comment by yaghmr** [comment]
Thanks again.
