### ISSUE TITLE
Job state doesn't change

### ISSUE THREAD

**Issue by yaghmr** [seomoz/qless-py#23]
I have this code:

```
j = client.jobs[job_id]
status = j.state

while(status != "complete" and status != "failed"):
    status = j.state
    print status
    if (status != "complete" and status != "failed"):
        time.sleep(5)
```

 ```status``` never change, is always ```waiting``` (also if in Redis is ```complete```), and I have an infinite loop. Why so? What is wrong?

**Comment by dlecocq** [comment]
To get updates to the job's state, you have to keep invoking `client.jobs[job_id]`. The `Job` object itself doesn't re-check with the server for it's state with every `job.state` invocation. Try this:

```python
while client.jobs[job_id].state not in ('complete', 'failed'):
    time.sleep(5)
```

**Comment by yaghmr** [comment]
Works fine. Thanks!
