### ISSUE TITLE
Job timeout too short

### ISSUE THREAD

**Issue by yaghmr** [seomoz/qless-py#24]
Is possible to change a job timeout?
After a while I get a "Pubsub error" and in Redis history DB I have a "timed-out" error.

**Comment by yaghmr** [comment]
I set ```client.config['heartbeat']``` in the app. Is this the right way?

**Comment by dlecocq** [comment]
Sorry for the delay -- I was on vacation.

Yes, `client.config['heartbeat']` is one way. That impacts the default heartbeat interval for all queues. It can also be set specifically on a per-queue basis with `client.queues['queue'].heartbeat = 1800`

**Comment by yaghmr** [comment]
Thank you.
