### ISSUE TITLE
Remove a recurring job

### ISSUE THREAD

**Issue by yaghmr** [seomoz/qless-py#25]
It is possible to remove/stop a recurring job?

**Comment by dlecocq** [comment]
Yes:

```python
my_recurring_job = client.jobs[...]
my_recurring_job.cancel()
```

**Comment by yaghmr** [comment]
Thank you for the quick reply.

I have to delete by name, is possible?
And can I list all recurring jobs?

**Comment by dlecocq** [comment]
Yes, if you have the `jid` you can delete that recurring job.

To list all recurring jobs, you'll have to do so by queue:

```python
for counts in client.queues.counts:
    queue_name = counts['name']
    for jid in client.queues[name].recurring(0, -1):
        ...
```
