### ISSUE TITLE
JavaScript Bindings

### ISSUE THREAD

**Issue by yaghmr** [seomoz/qless-py#28]
Is planned a JS binding of qless?
Is it possible easily?

**Comment by dlecocq** [comment]
At one point, we made a vague attempt at producing javascript bindings but without a project that actually needed those bindings, it fell by the wayside.

It's absolutely possible, though I don't know that we'll have the time internally. If you decide to hack on them yourself, here are a few things to keep in mind:

- `qless-py` is considered the 'canonical' bindings and can be used as a reference for new clients
- the conventions of `qless-py` don't have to be followed dogmatically -- follow the conventions of the target language (JS in this case) first, and `qless-py` second
- tests should cover the invocation of the `qless-core` scripts, but the core scripts themselves have their own unit tests

**Comment by b4hand** [comment]
There are official qless javascript bindings available [here](https://github.com/seomoz/qless-js) now.
