### ISSUE TITLE
Progress mechanism

### ISSUE THREAD

**Issue by eliemichel** [seomoz/qless-py#33]
Is there already a mechanism for jobs to notify the server and their trackers about their progress? Something like `job.progress(0.27)` to notify that 27% of the job is done, for instance.

**Comment by dlecocq** [comment]
Sort of. When jobs heartbeat, they have the opportunity to update their data in `redis`. That can mean many different things, but that can also mean updating a progress indicator. For example, I might say:

```python
job['progress'] = 0.27
job.heartbeat()
```

This would update the job's data to be:

```python
{
    ...
    'progress': 0.27,
    ...
}
```

**Comment by eliemichel** [comment]
Oh right, this is great. :)
